{% set version = "2.0" %}
{% set hash = "4a1e75d12257dd841efc51f7769c99c35196e3418b7806cde244878d2b01ae66" %}

package:
  name: capytaine
  version: {{ version }}

source:
  url: https://github.com/capytaine/capytaine/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  skip: true  # [py<37]
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - capytaine = capytaine.ui.cli:main

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - numpy <=1.26.2
    - meson-python
    - charset-normalizer
    - llvm-openmp  # [osx]
    - m2w64-toolchain  # [win]
    - libpython  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - xarray
    - llvm-openmp  # [osx]

test:
  imports:
    - capytaine
  requires:
    - pytest
    - hypothesis
    - pip
  source_files:
    - pytest/*.py
    - pytest/**/*
  commands:
    - pytest
    - capytaine --help

about:
  home: https://github.com/capytaine/capytaine
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python-based linear potential flow solver based on Nemoh

extra:
  recipe-maintainers:
    - mancellin
