{% set version = "1.2" %}
{% set hash = "b3dc967ffde8a0b9d815ab955b92a768711666236474776771b48f22e9e80f89" %}

package:
  name: capytaine
  version: {{ version }}

source:
  url: https://github.com/mancellin/capytaine/archive/v{{version}}.tar.gz
  sha256: {{ hash }}

build:
  skip: True  # [py<36]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - capytaine = capytaine.ui.cli:main

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - setuptools
    - numpy
    - llvm-openmp  # [osx]
    - m2w64-toolchain  # [win]
    - libpython  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - xarray
    - llvm-openmp  # [osx]

test:
  imports:
    - capytaine
  requires:
    - pytest
    - hypothesis
  source_files:
    - pytest/*.py
    - pytest/**/*
  commands:
    - pip install quadpy  # Optional dependency, needed for some of the tests
    - pytest
    - capytaine --help

about:
  home: https://github.com/mancellin/capytaine
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A Python-based linear potential flow solver based on Nemoh

extra:
  recipe-maintainers:
    - mancellin
