{% set version = "3.0.0" %}
{% set hash = "0d7cc6af6603a3abbe134471a10a0170aa82f3b3b60c44a1a2ec9d1a3d9cf5cb" %}

package:
  name: capytaine
  version: {{ version }}

source:
  url: https://github.com/capytaine/capytaine/archive/refs/tags/v{{ version }}.tar.gz

  # # For dry-run before making the release:
  # url: https://github.com/capytaine/capytaine/archive/refs/heads/master.tar.gz

  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - capytaine = capytaine.ui.cli:main

requirements:
  build:
    # uses m2w64 toolchain on windows, see conda_build_config.yaml
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - llvm-openmp  # [osx]
    # Temporary fix for https://github.com/conda-forge/ctng-compilers-feedstock/issues/225
    - gcc_impl_osx-64 {{ fortran_compiler_version }}.*  # [osx]
    # Temporary fix for https://github.com/conda-forge/m2w64-sysroot-feedstock/issues/23
    - m2w64-sysroot_win-64 ==12.0.0.r4.gg4f2fc60ca hd8ed1ab_10  # [win]
    - libwinpthread ==12.0.0.r4.gg4f2fc60ca h57928b3_10  # [win]
  host:
    - python
    - pip
    - numpy
    - meson-python
    - charset-normalizer
    - llvm-openmp  # [osx]
    - distutils-activate-mingw  # [win]
  run:
    - python
    - scipy
    - pandas
    - xarray
    - rich
    - llvm-openmp  # [osx]

test:
  imports:
    - capytaine
  requires:
    - pytest
    - pip
    # one test depends on implicit scalar conversion that was removed
    - numpy <2.4
  source_files:
    - pytest/*.py
    - pytest/**/*
  commands:
    - pytest
    - capytaine --help

about:
  home: https://github.com/capytaine/capytaine
  license: Apache-2.0
  license_file: LICENSE
  summary: A Python-based linear potential flow solver based on Nemoh

extra:
  recipe-maintainers:
    - mancellin
