{% set version = "2.1.dev0" %}

package:
  name: capytaine
  version: {{ version }}

source:
  git_url: https://github.com/capytaine/capytaine
  git_rev: 9e1233d8561587964c534023920b74a35a52f557
  git_depth: 1

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - capytaine = capytaine.ui.cli:main

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - meson-python
    - charset-normalizer
    - numpy
    - llvm-openmp  # [osx]
    - m2w64-toolchain  # [win]
    - libpython  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - xarray
    - rich
    - llvm-openmp  # [osx]

test:
  imports:
    - capytaine
  requires:
    - pytest
    - pip
  source_files:
    - pytest/*.py
    - pytest/**/*
  commands:
    - pytest
    - capytaine --help

about:
  home: https://github.com/capytaine/capytaine
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python-based linear potential flow solver based on Nemoh

extra:
  recipe-maintainers:
    - mancellin
