{% set version = "2.2" %}
# {% set hash = "f1945c02609fe16f58b691e7ad2f297087980fa6e7d1d1ca5826e478204e408e" %}

package:
  name: capytaine
  version: {{ version }}

source:
  git_url: https://github.com/capytaine/capytaine
  git_rev: master
  git_depth: 1
  # url: https://github.com/capytaine/capytaine/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: {{ hash }}

build:
  skip: True  # [py<38]
  skip: True  # [python_impl == 'pypy']
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - capytaine = capytaine.ui.cli:main

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - numpy <=1.26.2
    - meson-python
    - charset-normalizer
    - llvm-openmp  # [osx]
    - m2w64-toolchain  # [win]
    - libpython  # [win]
  run:
    - python
    - scipy
    - pandas
    - xarray
    - rich
    - llvm-openmp  # [osx]

test:
  imports:
    - capytaine
  requires:
    - pytest
    - pip
  source_files:
    - pytest/*.py
    - pytest/**/*
  commands:
    - pytest
    - capytaine --help

about:
  home: https://github.com/capytaine/capytaine
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python-based linear potential flow solver based on Nemoh

extra:
  recipe-maintainers:
    - mancellin
